function Hd = fir
%FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
% Generated on: 20-Mar-2023 00:44:09

% IIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are in Hz.
Fs = 1000;  % Sampling Frequency

Nb   = 8;   % Numerator Order
Na   = 8;   % Denominator Order
F3dB = 64;  % 3-dB Frequency

h  = fdesign.lowpass('Nb,Na,F3dB', Nb, Na, F3dB, Fs);
Hd = design(h, 'butter');

% [EOF]
